<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRwzgve4\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRwzgve4/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRwzgve4.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerRwzgve4\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerRwzgve4\appProdProjectContainer([
    'container.build_hash' => 'Rwzgve4',
    'container.build_id' => 'c3f07542',
    'container.build_time' => 1594654709,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRwzgve4');
