<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZcjsid5\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZcjsid5/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZcjsid5.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZcjsid5\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZcjsid5\appDevDebugProjectContainer([
    'container.build_hash' => 'Zcjsid5',
    'container.build_id' => 'b58eae5d',
    'container.build_time' => 1601308023,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZcjsid5');
